# Generated by Django 5.1.7 on 2025-07-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_Carrito', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('abandonado', 'Abandonado'), ('completado', 'Completado')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id_Carrito_Items', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_Pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('metodo_entrega', models.CharField(choices=[('domicilio', 'Entrega a domicilio'), ('tienda', 'Retiro en tienda')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_Pedido_Items', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
            ],
        ),
    ]
