# Generated by Django 5.1.7 on 2025-07-11 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logsstock',
            name='id_Admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logsstock',
            name='id_Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='productos.producto'),
        ),
    ]
